Fix typo in explanation of caching.spinnaker.io/ignore
Using the value `True` causes an exception:

java.lang.IllegalArgumentException: Illegally annotated resource for 'caching.spinnaker.io/ignore': com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'True': was expecting ('true', 'false' or 'null')
 at [Source: True; line: 1, column: 9]
 at com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifestAnnotater.getAnnotation(KubernetesManifestAnnotater.java:83) ~[clouddriver-kubernetes-1.751.0-SNAPSHOT.jar:1.751.0-SNAPSHOT]